# Generated by Django 6.0.3 on 2026-04-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('promo_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount'), ('FREE_ITEM', 'Free Item (Direct Vend)')], max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Percentage (0-100) or Fixed cents')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
            ],
        ),
    ]
