# Generated by Django 6.0.3 on 2026-04-02 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('machine_id', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=50)),
                ('price_cents', models.PositiveIntegerField(help_text='Original price of the item')),
                ('discount_cents', models.PositiveIntegerField(default=0, help_text='Discount from promotions')),
                ('amount_paid_cents', models.PositiveIntegerField(help_text='Final amount deducted from wallet')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (QR Scanned)'), ('PAID', 'Paid (Waiting for Machine)'), ('COMPLETED', 'Completed (Vended successfully)'), ('FAILED', 'Failed (Machine Error)'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When the QR session expires')),
            ],
        ),
    ]
