# Generated by Django 6.0.3 on 2026-04-07 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device_order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
