# Generated by Django 6.0.3 on 2026-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_device_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(help_text='Machine ID allowed to use this wallet', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description or location', max_length=255)),
            ],
        ),
    ]
